// action types
export const types = {
  // HTTP  calls
  FETCH_GENRE_REQUEST: 'FETCH_GENRE_REQUEST',
  FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
  FETCH_GENRE_ERROR: 'FETCH_GENRE_ERROR',
  
  FETCH_BOOK_REQUEST: 'FETCH_BOOK_REQUEST',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_ERROR: 'FETCH_BOOK_ERROR',
  
  // internal process only.
  ADD_BOOK_REQUEST: 'ADD_BOOK_REQUEST',
  ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
  
  REMOVE_BOOK_REQUEST: 'REMOVE_BOOK_REQUEST',
  REMOVE_BOOK_SUCCESS: 'REMOVE_BOOK_SUCCESS',
  
  PURCHASE_BOOK_REQUEST: 'PURCHASE_BOOK_REQUEST',
  PURCHASE_BOOK_SUCCESS: 'PURCHASE_BOOK_SUCCESS',
  
  CLEAN_BASKET_REQUEST: 'CLEAN_BASKET_REQUEST',
  CLEAN_BASKET_SUCCESS: 'CLEAN_BASKET_SUCCESS'
};